### ISSUE TITLE
Unable to integrate the plugin with Neo4j in docker

### ISSUE THREAD

**Issue by shwetank2174** [jbarrasa/neosemantics#94]
I have followed the recommended steps in the installation but I am unable to integrate the plugin when I am running Neo4j in docker. 
call.dbms.procedures() doesn't show the added procedures.
Also need to add APOC. Please help me with the procedure.

**Comment by dg-datavisyn** [comment]
Same problem here. There are no error messages.

The ping works, but when i want to integrate my data the error message says:

``` Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `semantics.importRDF` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.```

**Comment by jbarrasa** [comment]
This section in the APOC manual should be useful? 

http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.4/installation/#_using_apoc_with_the_neo4j_docker_image

I would expect the same to work with neosemantics.

Let me know if it helps.

JB.

**Comment by dg-datavisyn** [comment]
Hi.

Thanks for the quick response. I integrated APOC and neosemantics exactly the same way. I can see all the apoc.procedures but none of the semantics. I will go through the APOC tutorials again and follow-up with this thread as soon as I have some results.

Best wishes 
Dominic

**Comment by dg-datavisyn** [comment]
Now it works. The whitelist entries were missing in my docker-compse file. Here the working example:

```yaml
db_neo4j:
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_dbms_unmanaged__extension__classes=semantics.extension=/rdf
      - NEO4J_dbms_security_procedures_whitelist=apoc.*, semantics.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*, semantics.*
     ...
```
Thank you very much!
